// YiPet/src/chat/components/ChatInput/ChatInput.tsx
/**
 * YiPet Chat — ChatInput (rewritten)
 * Composition: ChatToolbar + DraftImageList + QuickButtons + TextArea + char count.
 */

import { FileSearchOutlined, PartitionOutlined } from '@ant-design/icons';
import { Input, Typography } from 'antd';
import type { KeyboardEvent } from 'react';
import { useMemo, useRef, useState } from 'react';
import type { ChatController } from '@/chat/controller';
import { ChatToolbar } from '../ChatToolbar/ChatToolbar';
import { DraftImageList } from '../DraftImageList/DraftImageList';
import { FileMentionDropdown } from '../FileMentionDropdown/FileMentionDropdown';
import { QuickButtons } from '../QuickButtons/QuickButtons';

const { TextArea } = Input;

const MAX_DRAFT_IMAGES = 4;

type SpeechRecognitionCtor = new () => {
  lang: string;
  interimResults: boolean;
  continuous: boolean;
  onresult: ((e: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null;
  onerror: ((e: { error?: string }) => void) | null;
  onend: (() => void) | null;
  start: () => void;
  stop: () => void;
};

function getSpeechRecognitionCtor(): SpeechRecognitionCtor | null {
  if (typeof window === 'undefined') return null;
  const w = window as unknown as {
    SpeechRecognition?: SpeechRecognitionCtor;
    webkitSpeechRecognition?: SpeechRecognitionCtor;
  };
  if (typeof w.SpeechRecognition === 'function') return w.SpeechRecognition;
  if (typeof w.webkitSpeechRecognition === 'function') return w.webkitSpeechRecognition;
  return null;
}

export interface ChatInputProps {
  controller: ChatController;
}

export function ChatInput(props: ChatInputProps) {
  const ctrl = props.controller;
  const s = ctrl.state;
  const disabled = !s.currentSessionId;
  const placeholder = 'Type a message... (Shift+Enter for newline, Enter to send)';
  const draftImages = s.draftImages || [];
  const voiceSupported = !!getSpeechRecognitionCtor();

  const taRef = useRef<HTMLTextAreaElement>(null);
  const [inputValue, setInputValue] = useState('');
  const [isComposing, setIsComposing] = useState(false);
  const [compositionEndTime, setCompositionEndTime] = useState(0);
  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef<InstanceType<SpeechRecognitionCtor> | null>(null);
  const voiceBaseTextRef = useRef('');
  const lastTemplateRef = useRef('');
  const historyIdxRef = useRef(-1);
  const preHistoryInputRef = useRef('');

  // ── @-mention file detection ──
  // Visible when the user has typed `@` at start-of-word, with no spaces
  // between the `@` and the cursor. `query` is whatever follows `@`.
  const { mentionVisible, mentionQuery, mentionAtIdx } = useMemo(() => {
    const text = inputValue;
    const ta = taRef.current;
    const caret = ta?.selectionStart ?? text.length;
    const lastAt = text.lastIndexOf('@', Math.min(caret, text.length));
    if (lastAt < 0) return { mentionVisible: false, mentionQuery: '', mentionAtIdx: -1 };
    // @ must be at start or preceded by whitespace
    if (lastAt > 0 && !/\s/.test(text[lastAt - 1])) {
      return { mentionVisible: false, mentionQuery: '', mentionAtIdx: -1 };
    }
    const after = text.slice(lastAt + 1, caret);
    // No spaces allowed inside the @query (one word)
    if (after.includes(' ')) {
      return { mentionVisible: false, mentionQuery: '', mentionAtIdx: -1 };
    }
    return { mentionVisible: true, mentionQuery: after, mentionAtIdx: lastAt };
  }, [inputValue]);

  const onMentionSelect = (path: string) => {
    if (mentionAtIdx < 0) return;
    const before = inputValue.slice(0, mentionAtIdx);
    const after = inputValue.slice(mentionAtIdx + 1 + mentionQuery.length);
    const next = (before + after).trim();
    setInputValue(next);
    ctrl.setRagScopeFromNode(path, true);
    if (!ctrl.state.knowledgeGrounded) ctrl.toggleKnowledgeGrounded();
  };

  // Sync template pushed from QuickButtons → input
  if (s.inputTemplate && s.inputTemplate !== lastTemplateRef.current) {
    lastTemplateRef.current = s.inputTemplate;
    setInputValue(s.inputTemplate);
  }

  const hasContent = !!inputValue.trim() || draftImages.length > 0;

  const send = () => {
    const text = inputValue.trim();
    const imgs = draftImages.length > 0 ? draftImages : undefined;
    if (!text && !imgs) return;
    ctrl.sendMessage(text, imgs);
    setInputValue('');
    lastTemplateRef.current = '';
    historyIdxRef.current = -1;
  };

  const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    // Mention dropdown is open — let it own navigation keys.
    if (mentionVisible) {
      if (e.key === 'Escape') {
        e.preventDefault();
        // Strip the @query so the dropdown stays closed next time.
        if (mentionAtIdx >= 0) {
          const before = inputValue.slice(0, mentionAtIdx);
          const after = inputValue.slice(mentionAtIdx + 1 + mentionQuery.length);
          setInputValue((before + after).trim());
        }
        return;
      }
      if (e.key === 'Enter' && !e.shiftKey) {
        // If matches exist, pick the first one instead of sending.
        const matches = ctrl.knowledgeFileMatches(mentionQuery, 1);
        if (matches.length > 0) {
          e.preventDefault();
          onMentionSelect(matches[0].path);
          return;
        }
        // No matches → fall through to send
      }
      // When mention is open, swallow ArrowUp/Down so they don't trigger
      // prompt history recall. (A future iteration could walk the dropdown.)
      if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        e.preventDefault();
        return;
      }
    }
    if (e.key === 'Escape') {
      e.preventDefault();
      setInputValue('');
      historyIdxRef.current = -1;
      return;
    }
    if (e.key === 'Enter') {
      if (e.nativeEvent.isComposing || isComposing) return;
      if (compositionEndTime > 0 && Date.now() - compositionEndTime < 100) return;
      if (e.shiftKey) return;
      e.preventDefault();
      if (s.isProcessing) return;
      send();
      return;
    }
    // Prompt history navigation (Pi-inspired shell recall).
    // ArrowUp at caret 0 / empty input → recall older prompt.
    // ArrowDown at caret end while navigating → recall newer (or clear).
    if (!e.metaKey && !e.ctrlKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown')) {
      const ta = taRef.current;
      const caret = ta?.selectionStart ?? inputValue.length;
      const atStart = caret === 0;
      const atEnd = caret === inputValue.length;
      if (e.key === 'ArrowUp' && (atStart || !inputValue)) {
        if (historyIdxRef.current === -1) preHistoryInputRef.current = inputValue;
        const rec = ctrl.recallPromptHistory(-1, historyIdxRef.current);
        if (rec) {
          e.preventDefault();
          historyIdxRef.current = rec.idx;
          setInputValue(rec.text);
        }
        return;
      }
      if (e.key === 'ArrowDown' && atEnd && historyIdxRef.current !== -1) {
        const rec = ctrl.recallPromptHistory(1, historyIdxRef.current);
        e.preventDefault();
        if (rec && rec.idx === -1) {
          historyIdxRef.current = -1;
          setInputValue(preHistoryInputRef.current);
        } else if (rec) {
          historyIdxRef.current = rec.idx;
          setInputValue(rec.text);
        }
        return;
      }
    }
  };

  const onPaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
    const items = e.clipboardData?.items;
    if (!items) return;
    const imageItems: DataTransferItem[] = [];
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.startsWith('image/')) imageItems.push(items[i]);
    }
    if (imageItems.length === 0) return;
    e.preventDefault();
    const remaining = MAX_DRAFT_IMAGES - draftImages.length;
    const toRead = imageItems.slice(0, remaining);
    let loaded = 0;
    const sources: string[] = new Array(toRead.length);
    toRead.forEach((item, i) => {
      const file = item.getAsFile();
      if (!file) {
        loaded++;
        return;
      }
      const reader = new FileReader();
      reader.onload = (ev) => {
        const src = ev.target?.result as string;
        if (src) sources[i] = src;
        loaded++;
        if (loaded === toRead.length) ctrl.addDraftImages(sources.filter(Boolean));
      };
      reader.onerror = () => {
        loaded++;
        if (loaded === toRead.length) ctrl.addDraftImages(sources.filter(Boolean));
      };
      reader.readAsDataURL(file);
    });
  };

  const onVoiceClick = () => {
    if (isRecording) {
      recognitionRef.current?.stop();
      recognitionRef.current = null;
      setIsRecording(false);
      return;
    }
    const Ctor = getSpeechRecognitionCtor();
    if (!Ctor) {
      ctrl.notifyVoiceUnsupported();
      return;
    }
    const ta = taRef.current;
    if (!ta) return;
    const rec = new Ctor();
    rec.lang = 'en-US';
    rec.interimResults = true;
    rec.continuous = true;
    voiceBaseTextRef.current = inputValue;
    rec.onresult = (e) => {
      let interim = '';
      let finalText = '';
      const r = e?.results;
      if (!r) return;
      for (let i = 0; i < r.length; i++) {
        const res = r[i];
        if (!res) continue;
        const txt = String(res[0]?.transcript || '');
        if (i < r.length - 1) finalText += txt;
        else interim += txt;
      }
      const next = voiceBaseTextRef.current + finalText + interim;
      setInputValue(next);
    };
    rec.onerror = (e) => {
      const code = e?.error || '';
      if (code === 'not-allowed' || code === 'service-not-allowed') {
        ctrl.notifyVoicePermissionDenied();
      }
      recognitionRef.current = null;
      setIsRecording(false);
    };
    rec.onend = () => {
      if (recognitionRef.current === rec) {
        recognitionRef.current = null;
        setIsRecording(false);
      }
    };
    try {
      rec.start();
      recognitionRef.current = rec;
      setIsRecording(true);
    } catch (err) {
      ctrl.notifyVoiceStartFailed((err as Error)?.message || 'Unknown error');
    }
  };

  const onClearInputClick = () => {
    setInputValue('');
    lastTemplateRef.current = '';
    if (draftImages.length > 0) ctrl.clearDraftImages();
  };

  return (
    <div className="yipet-chat-input-container">
      <ChatToolbar
        controller={ctrl}
        voiceSupported={voiceSupported}
        isRecording={isRecording}
        onVoiceClick={onVoiceClick}
        hasContent={hasContent}
        onClearInput={onClearInputClick}
      />

      {draftImages.length > 0 && (
        <DraftImageList
          images={draftImages}
          onRemove={(idx) => ctrl.removeDraftImage(idx)}
          onClear={() => ctrl.clearDraftImages()}
        />
      )}

      <QuickButtons controller={ctrl} />

      <div className="yipet-chat-input-row" style={{ position: 'relative' }}>
        <FileMentionDropdown
          controller={ctrl}
          query={mentionQuery}
          visible={mentionVisible}
          onClose={() => {
            // Strip the @ to dismiss the dropdown.
            if (mentionAtIdx >= 0) {
              const before = inputValue.slice(0, mentionAtIdx);
              const after = inputValue.slice(mentionAtIdx + 1 + mentionQuery.length);
              setInputValue((before + after).trim());
            }
          }}
          onSelect={onMentionSelect}
        />
        <TextArea
          ref={taRef as never}
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={onKeyDown}
          onPaste={onPaste}
          onCompositionStart={() => {
            setIsComposing(true);
            setCompositionEndTime(0);
          }}
          onCompositionUpdate={() => {
            setIsComposing(true);
            setCompositionEndTime(0);
          }}
          onCompositionEnd={() => {
            setIsComposing(false);
            setCompositionEndTime(Date.now());
          }}
          placeholder={placeholder}
          disabled={disabled}
          autoSize={{ minRows: 3, maxRows: 3 }}
          style={{ flex: 1, minHeight: 0 }}
          aria-label="Conversation input"
        />
        <div className="yipet-chat-input-meta">
          {s.knowledgeGrounded && (
            <>
              <button
                type="button"
                className="yipet-chat-preview-btn"
                onClick={() => ctrl.previewRagSources(inputValue)}
                disabled={
                  s.isProcessing ||
                  s.ragPreviewLoading ||
                  s.ragDecomposeLoading ||
                  !inputValue.trim()
                }
                title="Preview RAG sources (no LLM call)"
                aria-label="Preview RAG sources"
              >
                <FileSearchOutlined /> Preview sources
              </button>
              <button
                type="button"
                className="yipet-chat-preview-btn"
                onClick={() => ctrl.decomposeRagQuestion(inputValue)}
                disabled={
                  s.isProcessing ||
                  s.ragPreviewLoading ||
                  s.ragDecomposeLoading ||
                  !inputValue.trim()
                }
                title="Decompose into sub-questions (synchronous, may take a while)"
                aria-label="Decompose into sub-questions"
              >
                <PartitionOutlined /> Decompose
              </button>
            </>
          )}
          <Typography.Text type="secondary" style={{ fontSize: 11 }}>
            {inputValue.length} chars
          </Typography.Text>
        </div>
      </div>
    </div>
  );
}

// YiPet/src/chat/components/ChatInput.vue
<script setup lang="ts">
/**
 * YiPet Chat — ChatInput (Vue 3 SFC)
 */
import { computed, onMounted, onBeforeUnmount, ref, watch } from 'vue';
import { CircleClose } from '@element-plus/icons-vue';
import { useChatStore } from '../stores/chat';
import ChatToolbar from './ChatToolbar/ChatToolbar.vue';
import DraftImageList from './DraftImageList.vue';
import QuickButtons from './QuickButtons.vue';
import FileMentionDropdown from './FileMentionDropdown.vue';

const MAX_DRAFT_IMAGES = 4;

const store = useChatStore();
const s = store.state;

const disabled = computed(() => s.isProcessing);
const draftImages = computed(() => s.draftImages || []);

// Phase-aware placeholder (mirrors YiVad aiChat)
const placeholder = computed(() => {
  if (inputValue.value.startsWith('/')) return '/compact /clear /retry /stop /model /steer /followup /export /template — type a command';
  if (s.streamingPhase === 'fetching') return 'Fetching URL content...';
  if (s.streamingPhase === 'retrieving') return 'Retrieving knowledge base...';
  if (s.streamingPhase === 'thinking') return 'AI thinking...';
  if (s.streamingPhase === 'streaming') return 'AI responding...';
  if (s.webSearchEnabled && s.isProcessing) return 'Searching web...';
  return 'Ask anything, type @ to add files (Enter send, Shift+Enter newline)';
});

const inputValue = ref('');
const isComposing = ref(false);
const compositionEndTime = ref(0);
const lastTemplateRef = ref('');
const historyIdxRef = ref(-1);
const preHistoryInputRef = ref('');

// @-mention detection
const mentionQuery = ref('');
const mentionVisible = ref(false);
const mentionAtIdx = ref(-1);

function updateMention() {
  const text = inputValue.value;
  const lastAt = text.lastIndexOf('@');
  if (lastAt < 0) {
    mentionVisible.value = false;
    mentionQuery.value = '';
    mentionAtIdx.value = -1;
    return;
  }
  if (lastAt > 0 && !/\s/.test(text[lastAt - 1])) {
    mentionVisible.value = false;
    mentionQuery.value = '';
    mentionAtIdx.value = -1;
    return;
  }
  const after = text.slice(lastAt + 1);
  if (after.includes(' ')) {
    mentionVisible.value = false;
    mentionQuery.value = '';
    mentionAtIdx.value = -1;
    return;
  }
  mentionVisible.value = true;
  mentionQuery.value = after;
  mentionAtIdx.value = lastAt;
}

watch(inputValue, updateMention);

// Sync template from QuickButtons
watch(() => s.inputTemplate, (val) => {
  if (val && val !== lastTemplateRef.value) {
    lastTemplateRef.value = val;
    inputValue.value = val;
  }
});

const hasContent = computed(() => !!inputValue.value.trim() || draftImages.value.length > 0);

function slashKeyHandler(e: KeyboardEvent) {
  if (e.key !== '/') return;
  const target = e.target as HTMLElement | null;
  const tag = target?.tagName;
  if (tag === 'INPUT' || tag === 'TEXTAREA' || target?.isContentEditable === true) return;
  e.preventDefault();
  const textarea = document.querySelector('#yipet-chat-window .el-textarea__inner') as HTMLTextAreaElement | null;
  textarea?.focus();
}

onMounted(() => {
  window.addEventListener('keydown', slashKeyHandler);
});

onBeforeUnmount(() => {
  window.removeEventListener('keydown', slashKeyHandler);
});

function send() {
  const text = inputValue.value.trim();
  const imgs = draftImages.value.length > 0 ? draftImages.value : undefined;
  if (!text && !imgs) return;
  store.sendMessage(text, imgs);
  inputValue.value = '';
  lastTemplateRef.value = '';
  historyIdxRef.value = -1;
}

function onMentionSelect(path: string) {
  if (mentionAtIdx.value < 0) return;
  const before = inputValue.value.slice(0, mentionAtIdx.value);
  const after = inputValue.value.slice(mentionAtIdx.value + 1 + mentionQuery.value.length);
  inputValue.value = (before + after).trim();
  store.setRagScopeFromNode(path, true);
  if (!s.knowledgeGrounded) store.toggleKnowledgeGrounded();
}

function onMentionClose() {
  if (mentionAtIdx.value >= 0) {
    const before = inputValue.value.slice(0, mentionAtIdx.value);
    const after = inputValue.value.slice(mentionAtIdx.value + 1 + mentionQuery.value.length);
    inputValue.value = (before + after).trim();
  }
}

function onKeyDown(e: KeyboardEvent) {
  // Mention dropdown handling
  if (mentionVisible.value) {
    if (e.key === 'Escape') {
      e.preventDefault();
      onMentionClose();
      return;
    }
    if (e.key === 'Enter' && !e.shiftKey) {
      const matches = store.knowledgeFileMatches?.(mentionQuery.value, 1);
      if (matches && matches.length > 0) {
        e.preventDefault();
        onMentionSelect(matches[0].path);
        return;
      }
    }
    if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
      e.preventDefault();
      return;
    }
  }

  if (e.key === 'Escape') {
    e.preventDefault();
    if (s.isProcessing) { store.stopSending(); return; }
    inputValue.value = '';
    historyIdxRef.value = -1;
    return;
  }

  // Ctrl+K / Cmd+K: clear conversation
  if ((e.metaKey || e.ctrlKey) && e.key === 'k' && !s.isProcessing) {
    e.preventDefault();
    store.sendMessage('/clear');
    inputValue.value = '';
    return;
  }

  // Ctrl+L / Cmd+L: clear input
  if ((e.metaKey || e.ctrlKey) && e.key === 'l' && !s.isProcessing) {
    e.preventDefault();
    inputValue.value = '';
    return;
  }

  if (e.key === 'Enter') {
    if ((e as KeyboardEvent).isComposing || isComposing.value) return;
    if (compositionEndTime.value > 0 && Date.now() - compositionEndTime.value < 100) return;
    if (e.shiftKey) return;
    e.preventDefault();
    if (s.isProcessing) return;
    store.pushPromptHistory?.(inputValue.value);
    historyIdxRef.value = -1;
    send();
    return;
  }

  // Prompt history navigation
  if (!e.metaKey && !e.ctrlKey && (e.key === 'ArrowUp' || e.key === 'ArrowDown')) {
    if (e.key === 'ArrowUp' && (!inputValue.value || inputValue.value.length === 0)) {
      if (historyIdxRef.value === -1) preHistoryInputRef.value = inputValue.value;
      const rec = store.recallPromptHistory?.(-1, historyIdxRef.value);
      if (rec) {
        e.preventDefault();
        historyIdxRef.value = rec.idx;
        inputValue.value = rec.text;
      }
      return;
    }
    if (e.key === 'ArrowDown' && historyIdxRef.value !== -1) {
      const rec = store.recallPromptHistory?.(1, historyIdxRef.value);
      e.preventDefault();
      if (rec && rec.idx === -1) {
        historyIdxRef.value = -1;
        inputValue.value = preHistoryInputRef.value;
      } else if (rec) {
        historyIdxRef.value = rec.idx;
        inputValue.value = rec.text;
      }
      return;
    }
  }
}

function onPaste(e: ClipboardEvent) {
  const items = e.clipboardData?.items;
  if (!items) return;
  const imageItems: DataTransferItem[] = [];
  for (let i = 0; i < items.length; i++) {
    if (items[i].type.startsWith('image/')) imageItems.push(items[i]);
  }
  if (imageItems.length === 0) return;
  e.preventDefault();
  const remaining = MAX_DRAFT_IMAGES - draftImages.value.length;
  const toRead = imageItems.slice(0, remaining);
  let loaded = 0;
  const sources: string[] = new Array(toRead.length);
  toRead.forEach((item, i) => {
    const file = item.getAsFile();
    if (!file) {
      loaded++;
      return;
    }
    const reader = new FileReader();
    reader.onload = (ev) => {
      const src = ev.target?.result as string;
      if (src) sources[i] = src;
      loaded++;
      if (loaded === toRead.length) store.addDraftImages?.(sources.filter(Boolean));
    };
    reader.onerror = () => {
      loaded++;
      if (loaded === toRead.length) store.addDraftImages?.(sources.filter(Boolean));
    };
    reader.readAsDataURL(file);
  });
}
</script>

<template>
  <div class="yipet-chat-input-container">
    <ChatToolbar :has-content="hasContent" @clear-input="inputValue = ''; lastTemplateRef = ''; store.clearDraftImages?.()" />

    <DraftImageList
      v-if="draftImages.length > 0"
      :images="draftImages"
      @remove="(idx: number) => store.removeDraftImage?.(idx)"
      @clear="store.clearDraftImages?.()"
    />

    <QuickButtons />

    <div class="yipet-chat-input-row">
      <div class="yipet-chat-textarea-wrap">
        <FileMentionDropdown
          :query="mentionQuery"
          :visible="mentionVisible"
          @close="onMentionClose"
          @select="onMentionSelect"
        />
        <el-input
          v-model="inputValue"
          type="textarea"
          :autosize="{ minRows: 1, maxRows: 6 }"
          :placeholder="placeholder"
          :disabled="disabled"
          resize="none"
          aria-label="Conversation input"
          @keydown="onKeyDown"
          @paste="onPaste"
          @compositionstart="isComposing = true; compositionEndTime = 0"
          @compositionupdate="isComposing = true; compositionEndTime = 0"
          @compositionend="isComposing = false; compositionEndTime = Date.now()"
        />
      </div>
      <el-tooltip content="Clear input" placement="bottom">
        <el-button
          v-show="hasContent"
          circle
          size="default"
          :icon="CircleClose"
          @click="inputValue = ''; lastTemplateRef = ''; store.clearDraftImages?.()"
        />
      </el-tooltip>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.yipet-chat-input-container {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.yipet-chat-input-row {
  display: flex;
  gap: 6px;
  align-items: flex-end;
  position: relative;
}

.yipet-chat-textarea-wrap {
  position: relative;
  flex: 1;
  min-width: 0;
}

// el-input textarea dark theme
:deep(.el-textarea__inner) {
  background: var(--input-bg, #181730);
  border: 1px solid rgba(var(--primary-rgb, 99, 102, 241), 0.25);
  color: var(--text-primary, #f5f3ff);
  font-size: 13px;
  font-family: inherit;
  line-height: 1.5;
  border-radius: 8px;
  padding: 8px 10px;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;

  &::placeholder { color: var(--placeholder-color, rgba(212, 208, 232, 0.5)); }
  &:focus {
    border-color: var(--primary-light, #818cf8);
    box-shadow: 0 0 0 3px rgba(var(--primary-rgb, 99, 102, 241), 0.2);
  }
}

.send-btn {
  align-self: flex-end;
  flex-shrink: 0;
  --el-button-bg-color: rgba(var(--primary-rgb, 99, 102, 241), 0.15);
  --el-button-border-color: rgba(var(--primary-rgb, 99, 102, 241), 0.35);
  --el-button-text-color: var(--primary-light, #818cf8);
  --el-button-hover-bg-color: rgba(var(--primary-rgb, 99, 102, 241), 0.25);
  --el-button-hover-border-color: var(--primary-light, #818cf8);
  --el-button-hover-text-color: #fff;
  transition: all 0.15s;

  &:disabled {
    --el-button-bg-color: transparent;
    --el-button-border-color: rgba(var(--primary-rgb, 99, 102, 241), 0.15);
    --el-button-text-color: var(--text-secondary, #d4d0e8);
    opacity: 0.4;
  }
}

.yipet-chat-input-meta {
  position: absolute;
  right: 8px;
  bottom: 4px;
  display: flex;
  align-items: center;
  gap: 6px;
}

.chat-hint {
  font-size: 11px;
  color: var(--text-secondary, #d4d0e8);
  kbd {
    display: inline-block;
    min-width: 16px;
    padding: 1px 5px;
    font-family: 'SF Mono', 'Menlo', monospace;
    font-size: 11px;
    color: var(--text-secondary, #d4d0e8);
    background: rgba(var(--primary-rgb, 99, 102, 241), 0.1);
    border: 1px solid rgba(var(--primary-rgb, 99, 102, 241), 0.2);
    border-radius: 3px;
  }
}

.chat-actions {
  display: flex;
  gap: 8px;
}

</style>
