// YiPet/src/chat/components/DraftImageList/DraftImageList.tsx
import { CloseOutlined, DeleteOutlined } from '@ant-design/icons';
import { Button, Image } from 'antd';
import type { FC } from 'react';
import './DraftImageList.css';

export interface DraftImageListProps {
  images: string[];
  onRemove: (index: number) => void;
  onClear: () => void;
}

export const DraftImageList: FC<DraftImageListProps> = ({ images, onRemove, onClear }) => {
  if (!images.length) return null;
  return (
    <div className="di-list">
      {images.map((src, idx) => (
        <div className="di-item" key={`${idx}-${src.slice(0, 24)}`}>
          <Image src={src} alt={`Pending image ${idx + 1}`} className="di-img" preview={{ src }} />
          <Button
            className="di-remove"
            size="small"
            shape="circle"
            icon={<CloseOutlined />}
            onClick={(e) => {
              e.stopPropagation();
              onRemove(idx);
            }}
          />
        </div>
      ))}
      <Button
        className="di-clear"
        size="small"
        type="text"
        icon={<DeleteOutlined />}
        onClick={onClear}
      >
        Clear images ({images.length})
      </Button>
    </div>
  );
};

// YiVad/src/views/aiChat/components/DraftImageList.vue
<script setup lang="ts" name="aiChatDraftImageList">
import { Close, DeleteFilled } from "@element-plus/icons-vue";

defineProps<{
  images: string[];
}>();

const emit = defineEmits<{
  (e: "remove", index: number): void;
  (e: "clear"): void;
  (e: "preview", src: string): void;
}>();
</script>

<template>
  <div v-if="images.length" class="di-list">
    <div v-for="(src, idx) in images" :key="`${idx}-${src.slice(0, 24)}`" class="di-item" @click="emit('preview', src)">
      <img :src="src" class="di-img" :alt="`Pending image ${idx + 1}`" />
      <el-button class="di-remove" size="small" circle :icon="Close" @click.stop="emit('remove', idx)" />
    </div>
    <el-button class="di-clear" size="small" text :icon="DeleteFilled" @click="emit('clear')">
      Clear images ({{ images.length }})
    </el-button>
  </div>
</template>

<style scoped lang="scss">
.di-list {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
  padding: 4px 0;
}
.di-item {
  position: relative;
  width: 56px;
  height: 56px;
  overflow: hidden;
  cursor: zoom-in;
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 6px;
}
.di-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.di-remove {
  position: absolute;
  top: 2px;
  right: 2px;
  width: 18px !important;
  height: 18px !important;
  min-height: 18px !important;
  padding: 0 !important;
}
.di-clear {
  margin-left: 4px;
}
</style>
