// YiPet/src/chat/components/MessageBubble/MessageBubble.tsx
/**
 * YiPet Chat — MessageBubble (rewritten)
 * Mirrors YiVad aiChat MessageBubble: typing indicator, error/aborted tags,
 * multi-image, copy feedback, like/dislike, retry label.
 */

import {
  CopyOutlined,
  DeleteOutlined,
  DislikeFilled,
  DislikeOutlined,
  EditOutlined,
  LikeFilled,
  LikeOutlined,
  ReloadOutlined,
  SendOutlined,
} from '@ant-design/icons';
import { Button, Modal, Tooltip, Typography } from 'antd';
import { useEffect, useState } from 'react';
import type { ChatController } from '@/chat/controller';
import type { Message } from '@/chat/types';
import { formatTime, renderMarkdown } from '@/chat/utils';
import './MessageBubble.css';

export interface MessageBubbleProps {
  controller: ChatController;
  message: Message;
  index: number;
  totalMessages: number;
}

export function MessageBubble(props: MessageBubbleProps) {
  const { controller: ctrl, message: msg, index } = props;
  const s = ctrl.state;
  const isUser = msg.type === 'user';
  const hasContent = !!(msg.content || '').trim();
  const images = msg.imageDataUrls ?? (msg.imageDataUrl ? [msg.imageDataUrl] : []);
  const empty = !hasContent && images.length === 0;
  const streaming = !!msg.streaming;
  const copyState = s.copyFeedback[String(msg.timestamp)] || '';
  const rating = s.feedback[msg.timestamp] || null;
  const showRetryLabel = !!(msg.error || msg.aborted);

  // local edit modal state
  const [editOpen, setEditOpen] = useState(false);
  const [editValue, setEditValue] = useState('');

  useEffect(() => {
    if (editOpen) setEditValue(msg.content || '');
  }, [editOpen, msg.content]);

  const onEditSave = () => {
    ctrl.editMessage(index, editValue);
    setEditOpen(false);
  };

  const onDeleteConfirm = () => {
    Modal.confirm({
      title: 'Delete message',
      content: 'Delete this message?',
      okText: 'Delete',
      cancelText: 'Cancel',
      okButtonProps: { danger: true },
      onOk: () => ctrl.deleteMessage(index),
    });
  };

  return (
    <div
      className={`mb-bubble ${isUser ? 'mb-bubble--user' : 'mb-bubble--pet'} ${
        msg.error ? 'mb-bubble--error' : ''
      } ${msg.aborted ? 'mb-bubble--aborted' : ''}`}
      data-chat-idx={String(index)}
    >
      <div className="mb-content">
        {images.length > 0 && (
          <div className="mb-images">
            {images.map((src, i) => (
              <img
                key={`img-${i}-${src.slice(0, 12)}`}
                src={src}
                alt={`Image ${i + 1}`}
                className="mb-image"
              />
            ))}
          </div>
        )}
        {empty && !streaming ? (
          <div className="mb-empty" />
        ) : streaming ? (
          <div className="mb-typing" aria-label="Generating">
            <span className="mb-dot" />
            <span className="mb-dot" />
            <span className="mb-dot" />
          </div>
        ) : (
          <div
            className="mb-markdown markdown-content"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.content || '') }}
          />
        )}
        {msg.error && <div className="mb-tag mb-tag--error">Generation failed</div>}
        {msg.aborted && !msg.error && <div className="mb-tag mb-tag--aborted">Stopped</div>}
      </div>
      <div className="mb-meta">
        <div className="mb-actions">
          {!isUser ? (
            <>
              <Tooltip title="Copy">
                <Button
                  type="text"
                  size="small"
                  icon={<CopyOutlined />}
                  onClick={() => ctrl.copyMessage(msg.content || '', msg.timestamp)}
                >
                  {copyState === 'copied' ? 'copied' : ''}
                </Button>
              </Tooltip>
              <Tooltip title={showRetryLabel ? 'Retry' : 'Regenerate'}>
                <Button
                  type="text"
                  size="small"
                  icon={<ReloadOutlined />}
                  disabled={s.isProcessing}
                  onClick={() => ctrl.regenerateMessage(index)}
                >
                  {showRetryLabel ? 'Retry' : 'Regenerate'}
                </Button>
              </Tooltip>
              <Tooltip title="Delete">
                <Button
                  type="text"
                  size="small"
                  icon={<DeleteOutlined />}
                  disabled={s.isProcessing}
                  onClick={onDeleteConfirm}
                />
              </Tooltip>
              <Tooltip title="Like">
                <Button
                  type="text"
                  size="small"
                  icon={rating === 'like' ? <LikeFilled /> : <LikeOutlined />}
                  className={rating === 'like' ? 'mb-action--active' : ''}
                  onClick={() => ctrl.submitFeedback(msg.timestamp, 'like')}
                />
              </Tooltip>
              <Tooltip title="Dislike">
                <Button
                  type="text"
                  size="small"
                  danger={rating === 'dislike'}
                  icon={rating === 'dislike' ? <DislikeFilled /> : <DislikeOutlined />}
                  onClick={() => ctrl.submitFeedback(msg.timestamp, 'dislike')}
                />
              </Tooltip>
            </>
          ) : (
            <>
              <Tooltip title="Edit">
                <Button
                  type="text"
                  size="small"
                  icon={<EditOutlined />}
                  disabled={s.isProcessing}
                  onClick={() => setEditOpen(true)}
                />
              </Tooltip>
              <Tooltip title="Resend">
                <Button
                  type="text"
                  size="small"
                  icon={<SendOutlined />}
                  disabled={s.isProcessing}
                  onClick={() => ctrl.resendMessage(index)}
                />
              </Tooltip>
              <Tooltip title="Delete">
                <Button
                  type="text"
                  size="small"
                  icon={<DeleteOutlined />}
                  disabled={s.isProcessing}
                  onClick={onDeleteConfirm}
                />
              </Tooltip>
            </>
          )}
        </div>
        <time className="mb-time" dateTime={new Date(msg.timestamp).toISOString()}>
          {formatTime(msg.timestamp)}
        </time>
      </div>

      <Modal
        title="Edit message"
        open={editOpen}
        onOk={onEditSave}
        onCancel={() => setEditOpen(false)}
        okText="Save"
        cancelText="Cancel"
        zIndex={2147483647}
      >
        <Typography.Paragraph>
          <textarea
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            rows={5}
            style={{ width: '100%', resize: 'vertical' }}
            aria-label="Edit message content"
          />
        </Typography.Paragraph>
      </Modal>
    </div>
  );
}

// YiVad/src/views/aiChat/components/MessageBubble.vue
<script setup lang="ts" name="aiChatMessageBubble">
import { computed } from "vue";
import { useRouter } from "vue-router";
import { ElMessageBox } from "element-plus";
import { CopyDocument, Pointer, Star, RefreshRight, Delete, Edit, Promotion } from "@element-plus/icons-vue";
import dayjs from "dayjs";
import { useMarkdown } from "@/hooks/useMarkdown";
import { useAiChatStore } from "@/stores/modules/aiChat";
import RagSources from "@/components/RagSources.vue";
import type { ChatMessage } from "@/api/interface/yiweb";

const props = defineProps<{
  message: ChatMessage;
  index: number;
  streaming: boolean;
}>();

const store = useAiChatStore();
const router = useRouter();
const { render } = useMarkdown();

const isUser = computed(() => props.message.type === "user");
const html = computed(() => render(props.message.message ?? ""));
const time = computed(() => (props.message.timestamp ? dayjs(props.message.timestamp).format("MM/DD HH:mm:ss") : ""));
const copyLabel = computed(() => store.copyFeedback[String(props.message.timestamp)] || "Copy");
const feedbackRating = computed(() => store.feedback[props.message.timestamp] ?? null);
const showTyping = computed(() => props.streaming && !props.message.message?.trim() && !props.message.error);
const empty = computed(() => !props.message.message?.trim());
const showAbortedTag = computed(() => !!props.message.aborted && !props.message.error);
const showRetryLabel = computed(() => !!(props.message.error || props.message.aborted));

async function onRegenerate() {
  if (showRetryLabel.value) await store.retryLastMessage();
  else await store.regenerateMessage(props.index);
}

async function onDelete() {
  try {
    await ElMessageBox.confirm("Delete this message?", "Confirm delete", {
      confirmButtonText: "Delete",
      cancelButtonText: "Cancel",
      type: "warning"
    });
  } catch {
    return;
  }
  await store.deleteMessage(props.index);
}

function onOpenSourceFile(filePath: string) {
  if (!filePath) return;
  router.push({ path: "/knowledge/detail", query: { path: filePath } });
}

async function onEdit() {
  let res: { value?: string } | null = null;
  try {
    res = await ElMessageBox.prompt("Enter new content", "Edit message", {
      confirmButtonText: "Save",
      cancelButtonText: "Cancel",
      inputValue: props.message.message ?? ""
    });
  } catch {
    return;
  }
  const next = (res?.value ?? "").trim();
  if (!next) return;
  await store.editMessage(props.index, next);
}
</script>

<template>
  <div
    class="mb-bubble"
    :class="{ 'mb-bubble--user': isUser, 'mb-bubble--pet': !isUser, 'mb-bubble--error': props.message.error }"
  >
    <div class="mb-content">
      <div v-if="props.message.imageDataUrls?.length" class="mb-images">
        <img v-for="(src, i) in props.message.imageDataUrls" :key="i" :src="src" class="mb-img" alt="" />
      </div>
      <div v-if="empty && !showTyping" class="mb-empty" />
      <div v-else-if="showTyping" class="mb-typing">...</div>
      <div v-else class="mb-markdown" v-html="html" />
      <div v-if="props.message.error" class="mb-error-tag">Generation failed</div>
      <div v-else-if="showAbortedTag" class="mb-aborted-tag">Stopped</div>
      <RagSources
        v-if="!isUser && props.message.sources?.length"
        :sources="props.message.sources"
        @open-file="onOpenSourceFile"
      />
    </div>
    <div class="mb-meta">
      <div v-if="!isUser" class="mb-actions">
        <el-button size="small" text :icon="CopyDocument" @click="store.copyMessage(props.message)">{{ copyLabel }}</el-button>
        <el-button size="small" text :icon="RefreshRight" :disabled="store.sending" @click="onRegenerate">{{
          showRetryLabel ? "Retry" : "Regenerate"
        }}</el-button>
        <el-button size="small" text :icon="Delete" :disabled="store.sending" @click="onDelete">Delete</el-button>
        <el-button
          size="small"
          text
          :icon="Pointer"
          :type="feedbackRating === 'like' ? 'primary' : ''"
          @click="store.submitFeedback(props.message.timestamp, 'like')"
        />
        <el-button
          size="small"
          text
          :icon="Star"
          :type="feedbackRating === 'dislike' ? 'danger' : ''"
          @click="store.submitFeedback(props.message.timestamp, 'dislike')"
        />
      </div>
      <div v-else class="mb-actions">
        <el-button size="small" text :icon="Edit" :disabled="store.sending" @click="onEdit">Edit</el-button>
        <el-button size="small" text :icon="Promotion" :disabled="store.sending" @click="store.resendMessage(props.index)"
          >Resend</el-button
        >
        <el-button size="small" text :icon="Delete" :disabled="store.sending" @click="onDelete">Delete</el-button>
      </div>
      <time class="mb-time">{{ time }}</time>
    </div>
  </div>
</template>

<style scoped lang="scss">
.mb-bubble {
  display: flex;
  flex-direction: column;
  max-width: 85%;
  padding: 10px 14px;
  margin-bottom: 12px;
  font-size: 14px;
  line-height: 1.6;
  border-radius: 12px;
}
.mb-bubble--user {
  align-self: flex-end;
  background: var(--el-color-primary-light-9);
  border-radius: 12px 12px 4px;
}
.mb-bubble--pet {
  align-self: flex-start;
  background: var(--el-fill-color-light);
  border-radius: 12px 12px 12px 4px;
}
.mb-bubble--error {
  border: 1px solid var(--el-color-danger);
}
.mb-content {
  overflow-wrap: anywhere;
}
.mb-markdown :deep(p) {
  margin: 0 0 4px;
}
.mb-markdown :deep(pre) {
  padding: 8px;
  overflow-x: auto;
  font-size: 12px;
  background: var(--el-fill-color);
  border-radius: 6px;
}
.mb-markdown :deep(code) {
  font-family: "SF Mono", Menlo, monospace;
  font-size: 12px;
}
.mb-images {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 8px;
}
.mb-img {
  max-width: 200px;
  max-height: 200px;
  border-radius: 8px;
}
.mb-typing {
  font-style: italic;
  color: var(--el-text-color-secondary);
  animation: mb-blink 1s infinite;
}

@keyframes mb-blink {
  0%,
  100% {
    opacity: 0.4;
  }
  50% {
    opacity: 1;
  }
}
.mb-empty {
  min-height: 1px;
}
.mb-error-tag {
  margin-top: 4px;
  font-size: 12px;
  color: var(--el-color-danger);
}
.mb-aborted-tag {
  margin-top: 4px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.mb-meta {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: space-between;
  margin-top: 6px;
}
.mb-actions {
  display: flex;
  gap: 2px;
}
.mb-time {
  font-size: 11px;
  color: var(--el-text-color-placeholder);
}
</style>
